server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydemo?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
mybatis:

  mapper-locations: classpath:mapper/*.xml
